(defun c:tdk_dlugosc_rozkladu ()
  (setq tdk_dlugosc_rozkladu_liczba_pretow (getint "\nPodaj liczbe pretow: "))
  (setq tdk_dlugosc_rozkladu_liczba_pretow (- tdk_dlugosc_rozkladu_liczba_pretow 1))
  (setq tdk_dlugosc_rozkladu_rozstaw_pretow (getint "\nPodaj rozstaw pretow (mm): "))
  (setq tdk_dlugosc_rozkladu_dlugosc_rozkladu (* tdk_dlugosc_rozkladu_liczba_pretow tdk_dlugosc_rozkladu_rozstaw_pretow))
  (princ (strcat "Rozstaw pretow w rozkladzie wynosi: " (rtos (/ (float tdk_dlugosc_rozkladu_dlugosc_rozkladu) 1000) 2 4) " m"))
  (alert (strcat "Rozstaw pretow w rozkladzie wynosi: " (rtos (/ (float tdk_dlugosc_rozkladu_dlugosc_rozkladu) 1000) 2 4) " m"))
  (princ)
)